// flow-typed signature: 6fac0fef1e8529963d4c76969edf1fb2
// flow-typed version: <<STUB>>/@apollo/server_v^4.10.0/flow_v0.196.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/server/dist/cjs/ApolloServer' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/cachePolicy' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/determineApolloConfig' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/errorNormalize' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/errors' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/express4' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/constructor' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/context' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/graphql' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/http' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/incrementalDeliveryPolyfill' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/plugins' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/externalTypes/requestPipeline' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/generated/packageVersion' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/httpBatching' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/incrementalDeliveryPolyfill' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/internalErrorClasses' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/internalPlugin' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/cacheControl' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/disabled' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/drainHttpServer' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/drainHttpServer/stoppable' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/inlineTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/landingPage/default/getEmbeddedHTML' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/landingPage/default' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/landingPage/default/types' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/schemaIsSubgraph' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/schemaReporting' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/schemaReporting/schemaReporter' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/subscriptionCallback' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/traceTreeBuilder' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/defaultSendOperationsAsTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/durationHistogram' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/iterateOverTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/operationDerivedDataCache' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/options' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/plugin' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/stats' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/plugin/usageReporting/traceDetails' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/preventCsrf' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/requestPipeline' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/runHttpQuery' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/standalone' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/computeCoreSchemaHash' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/HeaderMap' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/invokeHooks' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/isDefined' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/makeGatewayGraphQLRequestContext' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/schemaInstrumentation' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/schemaManager' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/UnreachableCaseError' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/cjs/utils/urlForHttpServer' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/ApolloServer' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/cachePolicy' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/determineApolloConfig' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/errorNormalize' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/errors' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/express4' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/constructor' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/context' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/graphql' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/http' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/incrementalDeliveryPolyfill' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/plugins' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/externalTypes/requestPipeline' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/generated/packageVersion' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/httpBatching' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/incrementalDeliveryPolyfill' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/internalErrorClasses' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/internalPlugin' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/cacheControl' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/disabled' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/drainHttpServer' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/drainHttpServer/stoppable' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/inlineTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/landingPage/default/getEmbeddedHTML' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/landingPage/default' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/landingPage/default/types' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/schemaIsSubgraph' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/schemaReporting' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/schemaReporting/schemaReporter' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/subscriptionCallback' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/traceTreeBuilder' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/defaultSendOperationsAsTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/durationHistogram' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/iterateOverTrace' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/operationDerivedDataCache' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/options' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/plugin' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/stats' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/plugin/usageReporting/traceDetails' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/preventCsrf' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/requestPipeline' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/runHttpQuery' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/standalone' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/computeCoreSchemaHash' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/HeaderMap' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/invokeHooks' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/isDefined' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/makeGatewayGraphQLRequestContext' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/schemaInstrumentation' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/schemaManager' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/UnreachableCaseError' {
  declare module.exports: any;
}

declare module '@apollo/server/dist/esm/utils/urlForHttpServer' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/server/dist/cjs/ApolloServer.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/ApolloServer'>;
}
declare module '@apollo/server/dist/cjs/cachePolicy.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/cachePolicy'>;
}
declare module '@apollo/server/dist/cjs/determineApolloConfig.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/determineApolloConfig'>;
}
declare module '@apollo/server/dist/cjs/errorNormalize.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/errorNormalize'>;
}
declare module '@apollo/server/dist/cjs/errors/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/errors'>;
}
declare module '@apollo/server/dist/cjs/errors/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/errors'>;
}
declare module '@apollo/server/dist/cjs/express4/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/express4'>;
}
declare module '@apollo/server/dist/cjs/express4/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/express4'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/constructor.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/constructor'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/context.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/context'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/graphql.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/graphql'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/http.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/http'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/incrementalDeliveryPolyfill.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/incrementalDeliveryPolyfill'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/plugins.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/plugins'>;
}
declare module '@apollo/server/dist/cjs/externalTypes/requestPipeline.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/externalTypes/requestPipeline'>;
}
declare module '@apollo/server/dist/cjs/generated/packageVersion.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/generated/packageVersion'>;
}
declare module '@apollo/server/dist/cjs/httpBatching.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/httpBatching'>;
}
declare module '@apollo/server/dist/cjs/incrementalDeliveryPolyfill.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/incrementalDeliveryPolyfill'>;
}
declare module '@apollo/server/dist/cjs/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs'>;
}
declare module '@apollo/server/dist/cjs/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs'>;
}
declare module '@apollo/server/dist/cjs/internalErrorClasses.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/internalErrorClasses'>;
}
declare module '@apollo/server/dist/cjs/internalPlugin.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/internalPlugin'>;
}
declare module '@apollo/server/dist/cjs/plugin/cacheControl/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/cacheControl'>;
}
declare module '@apollo/server/dist/cjs/plugin/cacheControl/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/cacheControl'>;
}
declare module '@apollo/server/dist/cjs/plugin/disabled/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/disabled'>;
}
declare module '@apollo/server/dist/cjs/plugin/disabled/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/disabled'>;
}
declare module '@apollo/server/dist/cjs/plugin/drainHttpServer/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/drainHttpServer'>;
}
declare module '@apollo/server/dist/cjs/plugin/drainHttpServer/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/drainHttpServer'>;
}
declare module '@apollo/server/dist/cjs/plugin/drainHttpServer/stoppable.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/drainHttpServer/stoppable'>;
}
declare module '@apollo/server/dist/cjs/plugin/inlineTrace/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/inlineTrace'>;
}
declare module '@apollo/server/dist/cjs/plugin/inlineTrace/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/inlineTrace'>;
}
declare module '@apollo/server/dist/cjs/plugin/landingPage/default/getEmbeddedHTML.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/landingPage/default/getEmbeddedHTML'>;
}
declare module '@apollo/server/dist/cjs/plugin/landingPage/default/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/landingPage/default'>;
}
declare module '@apollo/server/dist/cjs/plugin/landingPage/default/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/landingPage/default'>;
}
declare module '@apollo/server/dist/cjs/plugin/landingPage/default/types.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/landingPage/default/types'>;
}
declare module '@apollo/server/dist/cjs/plugin/schemaIsSubgraph.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/schemaIsSubgraph'>;
}
declare module '@apollo/server/dist/cjs/plugin/schemaReporting/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/schemaReporting'>;
}
declare module '@apollo/server/dist/cjs/plugin/schemaReporting/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/schemaReporting'>;
}
declare module '@apollo/server/dist/cjs/plugin/schemaReporting/schemaReporter.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/schemaReporting/schemaReporter'>;
}
declare module '@apollo/server/dist/cjs/plugin/subscriptionCallback/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/subscriptionCallback'>;
}
declare module '@apollo/server/dist/cjs/plugin/subscriptionCallback/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/subscriptionCallback'>;
}
declare module '@apollo/server/dist/cjs/plugin/traceTreeBuilder.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/traceTreeBuilder'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/defaultSendOperationsAsTrace.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/defaultSendOperationsAsTrace'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/durationHistogram.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/durationHistogram'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/iterateOverTrace.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/iterateOverTrace'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/operationDerivedDataCache.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/operationDerivedDataCache'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/options.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/options'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/plugin.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/plugin'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/stats.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/stats'>;
}
declare module '@apollo/server/dist/cjs/plugin/usageReporting/traceDetails.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/plugin/usageReporting/traceDetails'>;
}
declare module '@apollo/server/dist/cjs/preventCsrf.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/preventCsrf'>;
}
declare module '@apollo/server/dist/cjs/requestPipeline.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/requestPipeline'>;
}
declare module '@apollo/server/dist/cjs/runHttpQuery.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/runHttpQuery'>;
}
declare module '@apollo/server/dist/cjs/standalone/index' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/standalone'>;
}
declare module '@apollo/server/dist/cjs/standalone/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/standalone'>;
}
declare module '@apollo/server/dist/cjs/utils/computeCoreSchemaHash.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/computeCoreSchemaHash'>;
}
declare module '@apollo/server/dist/cjs/utils/HeaderMap.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/HeaderMap'>;
}
declare module '@apollo/server/dist/cjs/utils/invokeHooks.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/invokeHooks'>;
}
declare module '@apollo/server/dist/cjs/utils/isDefined.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/isDefined'>;
}
declare module '@apollo/server/dist/cjs/utils/makeGatewayGraphQLRequestContext.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/makeGatewayGraphQLRequestContext'>;
}
declare module '@apollo/server/dist/cjs/utils/schemaInstrumentation.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/schemaInstrumentation'>;
}
declare module '@apollo/server/dist/cjs/utils/schemaManager.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/schemaManager'>;
}
declare module '@apollo/server/dist/cjs/utils/UnreachableCaseError.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/UnreachableCaseError'>;
}
declare module '@apollo/server/dist/cjs/utils/urlForHttpServer.js' {
  declare module.exports: $Exports<'@apollo/server/dist/cjs/utils/urlForHttpServer'>;
}
declare module '@apollo/server/dist/esm/ApolloServer.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/ApolloServer'>;
}
declare module '@apollo/server/dist/esm/cachePolicy.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/cachePolicy'>;
}
declare module '@apollo/server/dist/esm/determineApolloConfig.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/determineApolloConfig'>;
}
declare module '@apollo/server/dist/esm/errorNormalize.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/errorNormalize'>;
}
declare module '@apollo/server/dist/esm/errors/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/errors'>;
}
declare module '@apollo/server/dist/esm/errors/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/errors'>;
}
declare module '@apollo/server/dist/esm/express4/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/express4'>;
}
declare module '@apollo/server/dist/esm/express4/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/express4'>;
}
declare module '@apollo/server/dist/esm/externalTypes/constructor.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/constructor'>;
}
declare module '@apollo/server/dist/esm/externalTypes/context.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/context'>;
}
declare module '@apollo/server/dist/esm/externalTypes/graphql.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/graphql'>;
}
declare module '@apollo/server/dist/esm/externalTypes/http.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/http'>;
}
declare module '@apollo/server/dist/esm/externalTypes/incrementalDeliveryPolyfill.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/incrementalDeliveryPolyfill'>;
}
declare module '@apollo/server/dist/esm/externalTypes/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes'>;
}
declare module '@apollo/server/dist/esm/externalTypes/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes'>;
}
declare module '@apollo/server/dist/esm/externalTypes/plugins.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/plugins'>;
}
declare module '@apollo/server/dist/esm/externalTypes/requestPipeline.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/externalTypes/requestPipeline'>;
}
declare module '@apollo/server/dist/esm/generated/packageVersion.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/generated/packageVersion'>;
}
declare module '@apollo/server/dist/esm/httpBatching.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/httpBatching'>;
}
declare module '@apollo/server/dist/esm/incrementalDeliveryPolyfill.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/incrementalDeliveryPolyfill'>;
}
declare module '@apollo/server/dist/esm/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm'>;
}
declare module '@apollo/server/dist/esm/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm'>;
}
declare module '@apollo/server/dist/esm/internalErrorClasses.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/internalErrorClasses'>;
}
declare module '@apollo/server/dist/esm/internalPlugin.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/internalPlugin'>;
}
declare module '@apollo/server/dist/esm/plugin/cacheControl/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/cacheControl'>;
}
declare module '@apollo/server/dist/esm/plugin/cacheControl/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/cacheControl'>;
}
declare module '@apollo/server/dist/esm/plugin/disabled/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/disabled'>;
}
declare module '@apollo/server/dist/esm/plugin/disabled/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/disabled'>;
}
declare module '@apollo/server/dist/esm/plugin/drainHttpServer/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/drainHttpServer'>;
}
declare module '@apollo/server/dist/esm/plugin/drainHttpServer/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/drainHttpServer'>;
}
declare module '@apollo/server/dist/esm/plugin/drainHttpServer/stoppable.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/drainHttpServer/stoppable'>;
}
declare module '@apollo/server/dist/esm/plugin/inlineTrace/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/inlineTrace'>;
}
declare module '@apollo/server/dist/esm/plugin/inlineTrace/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/inlineTrace'>;
}
declare module '@apollo/server/dist/esm/plugin/landingPage/default/getEmbeddedHTML.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/landingPage/default/getEmbeddedHTML'>;
}
declare module '@apollo/server/dist/esm/plugin/landingPage/default/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/landingPage/default'>;
}
declare module '@apollo/server/dist/esm/plugin/landingPage/default/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/landingPage/default'>;
}
declare module '@apollo/server/dist/esm/plugin/landingPage/default/types.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/landingPage/default/types'>;
}
declare module '@apollo/server/dist/esm/plugin/schemaIsSubgraph.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/schemaIsSubgraph'>;
}
declare module '@apollo/server/dist/esm/plugin/schemaReporting/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/schemaReporting'>;
}
declare module '@apollo/server/dist/esm/plugin/schemaReporting/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/schemaReporting'>;
}
declare module '@apollo/server/dist/esm/plugin/schemaReporting/schemaReporter.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/schemaReporting/schemaReporter'>;
}
declare module '@apollo/server/dist/esm/plugin/subscriptionCallback/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/subscriptionCallback'>;
}
declare module '@apollo/server/dist/esm/plugin/subscriptionCallback/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/subscriptionCallback'>;
}
declare module '@apollo/server/dist/esm/plugin/traceTreeBuilder.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/traceTreeBuilder'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/defaultSendOperationsAsTrace.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/defaultSendOperationsAsTrace'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/durationHistogram.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/durationHistogram'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/iterateOverTrace.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/iterateOverTrace'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/operationDerivedDataCache.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/operationDerivedDataCache'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/options.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/options'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/plugin.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/plugin'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/stats.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/stats'>;
}
declare module '@apollo/server/dist/esm/plugin/usageReporting/traceDetails.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/plugin/usageReporting/traceDetails'>;
}
declare module '@apollo/server/dist/esm/preventCsrf.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/preventCsrf'>;
}
declare module '@apollo/server/dist/esm/requestPipeline.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/requestPipeline'>;
}
declare module '@apollo/server/dist/esm/runHttpQuery.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/runHttpQuery'>;
}
declare module '@apollo/server/dist/esm/standalone/index' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/standalone'>;
}
declare module '@apollo/server/dist/esm/standalone/index.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/standalone'>;
}
declare module '@apollo/server/dist/esm/utils/computeCoreSchemaHash.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/computeCoreSchemaHash'>;
}
declare module '@apollo/server/dist/esm/utils/HeaderMap.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/HeaderMap'>;
}
declare module '@apollo/server/dist/esm/utils/invokeHooks.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/invokeHooks'>;
}
declare module '@apollo/server/dist/esm/utils/isDefined.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/isDefined'>;
}
declare module '@apollo/server/dist/esm/utils/makeGatewayGraphQLRequestContext.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/makeGatewayGraphQLRequestContext'>;
}
declare module '@apollo/server/dist/esm/utils/schemaInstrumentation.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/schemaInstrumentation'>;
}
declare module '@apollo/server/dist/esm/utils/schemaManager.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/schemaManager'>;
}
declare module '@apollo/server/dist/esm/utils/UnreachableCaseError.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/UnreachableCaseError'>;
}
declare module '@apollo/server/dist/esm/utils/urlForHttpServer.js' {
  declare module.exports: $Exports<'@apollo/server/dist/esm/utils/urlForHttpServer'>;
}
