// flow-typed signature: 36e5ac93bf6db3416982a543a382eadb
// flow-typed version: <<STUB>>/@types/express_v^4.17.21/flow_v0.196.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/express' {
  declare module.exports: any;
}
