// flow-typed signature: b30e70e0e176a401d2c25c739e0583e4
// flow-typed version: <<STUB>>/test_v^3.3.0/flow_v0.196.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'test/bin/node--test-name-pattern' {
  declare module.exports: any;
}

declare module 'test/bin/node--test-only' {
  declare module.exports: any;
}

declare module 'test/bin/node--test' {
  declare module.exports: any;
}

declare module 'test/bin/node-core-test' {
  declare module.exports: any;
}

declare module 'test/example' {
  declare module.exports: any;
}

declare module 'test/lib/internal/abort_controller' {
  declare module.exports: any;
}

declare module 'test/lib/internal/assert' {
  declare module.exports: any;
}

declare module 'test/lib/internal/console/global' {
  declare module.exports: any;
}

declare module 'test/lib/internal/errors' {
  declare module.exports: any;
}

declare module 'test/lib/internal/main/test_runner' {
  declare module.exports: any;
}

declare module 'test/lib/internal/options' {
  declare module.exports: any;
}

declare module 'test/lib/internal/per_context/primordials' {
  declare module.exports: any;
}

declare module 'test/lib/internal/process/pre_execution' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/harness' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/mock' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/reporter/dot' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/reporter/spec' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/reporter/tap' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/runner' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/tap_checker' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/tap_lexer' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/tap_parser' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/test' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/tests_stream' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/utils' {
  declare module.exports: any;
}

declare module 'test/lib/internal/test_runner/yaml_to_js' {
  declare module.exports: any;
}

declare module 'test/lib/internal/timers' {
  declare module.exports: any;
}

declare module 'test/lib/internal/util' {
  declare module.exports: any;
}

declare module 'test/lib/internal/util/colors' {
  declare module.exports: any;
}

declare module 'test/lib/internal/util/inspect' {
  declare module.exports: any;
}

declare module 'test/lib/internal/util/inspector' {
  declare module.exports: any;
}

declare module 'test/lib/internal/util/types' {
  declare module.exports: any;
}

declare module 'test/lib/internal/validators' {
  declare module.exports: any;
}

declare module 'test/lib/test' {
  declare module.exports: any;
}

declare module 'test/lib/timers/promises' {
  declare module.exports: any;
}

declare module 'test/test/common/fixtures' {
  declare module.exports: any;
}

declare module 'test/test/common' {
  declare module.exports: any;
}

declare module 'test/test/common/tmpdir' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/custom_reporters/custom' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/index.test' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/invalid-tap' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/nested' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/never_ending_async' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/never_ending_sync' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/node_modules/test-nm' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/protoMutation' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/reporters' {
  declare module.exports: any;
}

declare module 'test/test/fixtures/test-runner/subdir/subdir_test' {
  declare module.exports: any;
}

declare module 'test/test/message' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_abort_suite' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_abort' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_describe_nested' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_desctibe_it' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_hooks' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_no_refs' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_no_tests' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_only_tests' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_output_cli' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_output_dot_reporter' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_output_spec_reporter' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_output' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_test_name_pattern_with_only' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_test_name_pattern' {
  declare module.exports: any;
}

declare module 'test/test/message/test_runner_unresolved_promise' {
  declare module.exports: any;
}

declare module 'test/test/node-core-test' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-cli' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-concurrency' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-exit-code' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-extraneous-async-activity' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-misc' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-mocking' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-option-validation' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-reporters' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-string-to-regexp' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-tap-checker' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-tap-lexer' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-tap-parser-stream' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-tap-parser' {
  declare module.exports: any;
}

declare module 'test/test/parallel/test-runner-test-filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'test/bin/node--test-name-pattern.js' {
  declare module.exports: $Exports<'test/bin/node--test-name-pattern'>;
}
declare module 'test/bin/node--test-only.js' {
  declare module.exports: $Exports<'test/bin/node--test-only'>;
}
declare module 'test/bin/node--test.js' {
  declare module.exports: $Exports<'test/bin/node--test'>;
}
declare module 'test/bin/node-core-test.js' {
  declare module.exports: $Exports<'test/bin/node-core-test'>;
}
declare module 'test/example.js' {
  declare module.exports: $Exports<'test/example'>;
}
declare module 'test/lib/internal/abort_controller.js' {
  declare module.exports: $Exports<'test/lib/internal/abort_controller'>;
}
declare module 'test/lib/internal/assert.js' {
  declare module.exports: $Exports<'test/lib/internal/assert'>;
}
declare module 'test/lib/internal/console/global.js' {
  declare module.exports: $Exports<'test/lib/internal/console/global'>;
}
declare module 'test/lib/internal/errors.js' {
  declare module.exports: $Exports<'test/lib/internal/errors'>;
}
declare module 'test/lib/internal/main/test_runner.js' {
  declare module.exports: $Exports<'test/lib/internal/main/test_runner'>;
}
declare module 'test/lib/internal/options.js' {
  declare module.exports: $Exports<'test/lib/internal/options'>;
}
declare module 'test/lib/internal/per_context/primordials.js' {
  declare module.exports: $Exports<'test/lib/internal/per_context/primordials'>;
}
declare module 'test/lib/internal/process/pre_execution.js' {
  declare module.exports: $Exports<'test/lib/internal/process/pre_execution'>;
}
declare module 'test/lib/internal/test_runner/harness.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/harness'>;
}
declare module 'test/lib/internal/test_runner/mock.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/mock'>;
}
declare module 'test/lib/internal/test_runner/reporter/dot.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/reporter/dot'>;
}
declare module 'test/lib/internal/test_runner/reporter/spec.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/reporter/spec'>;
}
declare module 'test/lib/internal/test_runner/reporter/tap.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/reporter/tap'>;
}
declare module 'test/lib/internal/test_runner/runner.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/runner'>;
}
declare module 'test/lib/internal/test_runner/tap_checker.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/tap_checker'>;
}
declare module 'test/lib/internal/test_runner/tap_lexer.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/tap_lexer'>;
}
declare module 'test/lib/internal/test_runner/tap_parser.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/tap_parser'>;
}
declare module 'test/lib/internal/test_runner/test.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/test'>;
}
declare module 'test/lib/internal/test_runner/tests_stream.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/tests_stream'>;
}
declare module 'test/lib/internal/test_runner/utils.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/utils'>;
}
declare module 'test/lib/internal/test_runner/yaml_to_js.js' {
  declare module.exports: $Exports<'test/lib/internal/test_runner/yaml_to_js'>;
}
declare module 'test/lib/internal/timers.js' {
  declare module.exports: $Exports<'test/lib/internal/timers'>;
}
declare module 'test/lib/internal/util.js' {
  declare module.exports: $Exports<'test/lib/internal/util'>;
}
declare module 'test/lib/internal/util/colors.js' {
  declare module.exports: $Exports<'test/lib/internal/util/colors'>;
}
declare module 'test/lib/internal/util/inspect.js' {
  declare module.exports: $Exports<'test/lib/internal/util/inspect'>;
}
declare module 'test/lib/internal/util/inspector.js' {
  declare module.exports: $Exports<'test/lib/internal/util/inspector'>;
}
declare module 'test/lib/internal/util/types.js' {
  declare module.exports: $Exports<'test/lib/internal/util/types'>;
}
declare module 'test/lib/internal/validators.js' {
  declare module.exports: $Exports<'test/lib/internal/validators'>;
}
declare module 'test/lib/test.js' {
  declare module.exports: $Exports<'test/lib/test'>;
}
declare module 'test/lib/timers/promises.js' {
  declare module.exports: $Exports<'test/lib/timers/promises'>;
}
declare module 'test/test/common/fixtures.js' {
  declare module.exports: $Exports<'test/test/common/fixtures'>;
}
declare module 'test/test/common/index' {
  declare module.exports: $Exports<'test/test/common'>;
}
declare module 'test/test/common/index.js' {
  declare module.exports: $Exports<'test/test/common'>;
}
declare module 'test/test/common/tmpdir.js' {
  declare module.exports: $Exports<'test/test/common/tmpdir'>;
}
declare module 'test/test/fixtures/test-runner/custom_reporters/custom.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/custom_reporters/custom'>;
}
declare module 'test/test/fixtures/test-runner/index' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner'>;
}
declare module 'test/test/fixtures/test-runner/index.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner'>;
}
declare module 'test/test/fixtures/test-runner/index.test.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/index.test'>;
}
declare module 'test/test/fixtures/test-runner/invalid-tap.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/invalid-tap'>;
}
declare module 'test/test/fixtures/test-runner/nested.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/nested'>;
}
declare module 'test/test/fixtures/test-runner/never_ending_async.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/never_ending_async'>;
}
declare module 'test/test/fixtures/test-runner/never_ending_sync.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/never_ending_sync'>;
}
declare module 'test/test/fixtures/test-runner/node_modules/test-nm.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/node_modules/test-nm'>;
}
declare module 'test/test/fixtures/test-runner/protoMutation.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/protoMutation'>;
}
declare module 'test/test/fixtures/test-runner/reporters.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/reporters'>;
}
declare module 'test/test/fixtures/test-runner/subdir/subdir_test.js' {
  declare module.exports: $Exports<'test/test/fixtures/test-runner/subdir/subdir_test'>;
}
declare module 'test/test/message.js' {
  declare module.exports: $Exports<'test/test/message'>;
}
declare module 'test/test/message/test_runner_abort_suite.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_abort_suite'>;
}
declare module 'test/test/message/test_runner_abort.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_abort'>;
}
declare module 'test/test/message/test_runner_describe_nested.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_describe_nested'>;
}
declare module 'test/test/message/test_runner_desctibe_it.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_desctibe_it'>;
}
declare module 'test/test/message/test_runner_hooks.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_hooks'>;
}
declare module 'test/test/message/test_runner_no_refs.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_no_refs'>;
}
declare module 'test/test/message/test_runner_no_tests.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_no_tests'>;
}
declare module 'test/test/message/test_runner_only_tests.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_only_tests'>;
}
declare module 'test/test/message/test_runner_output_cli.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_output_cli'>;
}
declare module 'test/test/message/test_runner_output_dot_reporter.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_output_dot_reporter'>;
}
declare module 'test/test/message/test_runner_output_spec_reporter.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_output_spec_reporter'>;
}
declare module 'test/test/message/test_runner_output.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_output'>;
}
declare module 'test/test/message/test_runner_test_name_pattern_with_only.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_test_name_pattern_with_only'>;
}
declare module 'test/test/message/test_runner_test_name_pattern.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_test_name_pattern'>;
}
declare module 'test/test/message/test_runner_unresolved_promise.js' {
  declare module.exports: $Exports<'test/test/message/test_runner_unresolved_promise'>;
}
declare module 'test/test/node-core-test.js' {
  declare module.exports: $Exports<'test/test/node-core-test'>;
}
declare module 'test/test/parallel/test-runner-cli.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-cli'>;
}
declare module 'test/test/parallel/test-runner-concurrency.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-concurrency'>;
}
declare module 'test/test/parallel/test-runner-exit-code.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-exit-code'>;
}
declare module 'test/test/parallel/test-runner-extraneous-async-activity.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-extraneous-async-activity'>;
}
declare module 'test/test/parallel/test-runner-misc.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-misc'>;
}
declare module 'test/test/parallel/test-runner-mocking.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-mocking'>;
}
declare module 'test/test/parallel/test-runner-option-validation.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-option-validation'>;
}
declare module 'test/test/parallel/test-runner-reporters.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-reporters'>;
}
declare module 'test/test/parallel/test-runner-string-to-regexp.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-string-to-regexp'>;
}
declare module 'test/test/parallel/test-runner-tap-checker.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-tap-checker'>;
}
declare module 'test/test/parallel/test-runner-tap-lexer.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-tap-lexer'>;
}
declare module 'test/test/parallel/test-runner-tap-parser-stream.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-tap-parser-stream'>;
}
declare module 'test/test/parallel/test-runner-tap-parser.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-tap-parser'>;
}
declare module 'test/test/parallel/test-runner-test-filter.js' {
  declare module.exports: $Exports<'test/test/parallel/test-runner-test-filter'>;
}
